document.writeln("<article class=\"card article-card\">");
document.writeln("                <a href=\"Comment_kommisar.html\">");
document.writeln("                  <div class=\"card-image\">");
document.writeln("                    <div class=\"post-info\"> <span class=\"text-uppercase\">2024/?</span>");
document.writeln("                      <span class=\"text-uppercase\">13.?</span>");
document.writeln("                    </div>");
document.writeln("                    <img loading=\"lazy\" decoding=\"async\" src=\"images/post/wows_comment/kommisar/kommisar.png\" alt=\"Post Thumbnail\" class=\"w-100\">");
document.writeln("                  </div>");
document.writeln("                </a>");
document.writeln("                <div class=\"card-body px-0 pb-1\">");
document.writeln("                  <ul class=\"post-meta mb-2\">");
document.writeln("                    <li> ");
document.writeln("					  <a href=\"#!\">战舰世界</a>");
document.writeln("                      <a href=\"#!\">新船唠嗑</a>");
document.writeln("                    </li>");
document.writeln("                  </ul>");
document.writeln("                  <h2 class=\"h1\"><a class=\"post-title\" href=\"Comment_kommisar.html\">三栖纸船 - 科米萨尔评测</a></h2>");
document.writeln("                  <p class=\"card-text\"><b>! 文章内容暂未公开 !</b></p>");
document.writeln("                  <div class=\"content\"> <a class=\"read-more-btn\" href=\"Comment_kommisar.html\">阅读全文</a>");
document.writeln("                  </div>");
document.writeln("                </div>");
document.writeln("              </article>");