document.writeln("<article class=\"card article-card\">");
document.writeln("                <a href=\"devblog512.html\">");
document.writeln("                  <div class=\"card-image\">");
document.writeln("                    <div class=\"post-info\"> <span class=\"text-uppercase\">2024/2/21</span>");
document.writeln("                      <span class=\"text-uppercase\">13.1</span>");
document.writeln("                    </div>");
document.writeln("                    <img loading=\"lazy\" decoding=\"async\" src=\"images/devblog.jpg\" alt=\"Post Thumbnail\" class=\"w-100\">");
document.writeln("                  </div>");
document.writeln("                </a>");
document.writeln("                <div class=\"card-body px-0 pb-1\">");
document.writeln("                  <ul class=\"post-meta mb-2\">");
document.writeln("                    <li> ");
document.writeln("					  <a href=\"#!\">战舰世界</a>");
document.writeln("                      <a href=\"#!\">开发者日志</a>");
document.writeln("					  <a href=\"#!\">平衡性调整</a>");
document.writeln("					  <a href=\"#!\"><b>最新最热</b></a>");
document.writeln("                    </li>");
document.writeln("                  </ul>");
document.writeln("                  <h2 class=\"h1\"><a class=\"post-title\" href=\"devblog512.html\">测试船改动 - 封测13.1</a></h2>");
document.writeln("                  <p class=\"card-text\">根据测试结果，我们对英联邦巡洋舰线作出了平衡性调整。</p>");
document.writeln("                  <div class=\"content\"> <a class=\"read-more-btn\" href=\"devblog512.html\">阅读全文</a>");
document.writeln("                  </div>");
document.writeln("                </div>");
document.writeln("              </article>");