document.writeln("<article class=\'card article-card\'>");
document.writeln("                <a href=\'MC_classroom_sekai.html\'>");
document.writeln("                  <div class=\'card-image\'>");
document.writeln("                    <div class=\'post-info\'> <span class=\'text-uppercase\'>2024/2/22</span>");
document.writeln("                    </div>");
document.writeln("                    <img loading=\'lazy\' decoding=\'async\' src=\'images/post/mc/sekai/sekai_topper.png\' alt=\'Post Thumbnail\' class=\'w-100\'>");
document.writeln("                  </div>");
document.writeln("                </a>");
document.writeln("                <div class=\'card-body px-0 pb-1\'>");
document.writeln("                  <ul class=\'post-meta mb-2\'>");
document.writeln("                    <li> ");
document.writeln("					  <a href=\'#!\'>Minecraft</a>");
document.writeln("                    </li>");
document.writeln("                  </ul>");
document.writeln("                  <h2 class=\'h1\'><a class=\'post-title\' href=\'MC_classroom_sekai.html\'>MC服务器 - Classroom SEKAI</a></h2>");
document.writeln("                  <p class=\'card-text\'>欢迎你来mc服务器游玩</p>");
document.writeln("                  <div class=\'content\'> <a class=\'read-more-btn\' href=\'MC_classroom_sekai.html\'>阅读全文</a>");
document.writeln("                  </div>");
document.writeln("                </div>");
document.writeln("    </article>");