document.writeln("<article class=\'card article-card article-card-sm h-100\'>");
document.writeln("                <a href=\'pjsk1.html\'>");
document.writeln("                  <div class=\'card-image\'>");
document.writeln("                    <div class=\'post-info\'> ");
document.writeln("						<span class=\'text-uppercase\'>2024/2/21</span>");
document.writeln("                    </div>");
document.writeln("                    <img loading=\'lazy\' decoding=\'async\' src=\'images/post/PJSK/pjsk1/pjsk1.png\' alt=\'Post Thumbnail\' class=\'w-100\'>");
document.writeln("                  </div>");
document.writeln("                </a>");
document.writeln("                <div class=\'card-body px-0 pb-0\'>");
document.writeln("                  <ul class=\'post-meta mb-2\'>");
document.writeln("                    <li>");
document.writeln("					  <a href=\'#!\'>PJSK</a>");
document.writeln("                    </li>");
document.writeln("                  </ul>");
document.writeln("                  <h2><a class=\'post-title\' href=\'pjsk1.html\'>我还没有想好写什么</a></h2>");
document.writeln("                  <p class=\'card-text\'>先送你们一套自己p的图！对应活动hrk二混。</p>");
document.writeln("                  <div class=\'content\'> <a class=\'read-more-btn\' href=\'pjsk1.html\'>阅读全文</a>");
document.writeln("                  </div>");
document.writeln("                </div>");
document.writeln("              </article>");