document.writeln("<article class=\'card article-card\'>");
document.writeln("");
document.writeln("    <a href=\'#\'>");
document.writeln("        <div class=\'card-image\'>");
document.writeln("            <div class=\'post-info\'>");
document.writeln("				<span class=\'text-uppercase\'>2024/3/10</span>");
document.writeln("            </div>");
document.writeln("             <img loading=\'lazy\' decoding=\'async\' src=\'images/work_in_progress.png\' alt=\'Post Thumbnail\' class=\'w-100\'>");
document.writeln("        </div>");
document.writeln("	</a>");
document.writeln("    ");
document.writeln("	<div class=\'card-body px-0 pb-1\'>");
document.writeln("        <ul class=\'post-meta mb-2\'>");
document.writeln("			<li> ");
document.writeln("				<a href=\'#!\'>公告</a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("        <h2 class=\'h1\'><a class=\'post-title\' href=\'#\'>网站正在维护中……</a></h2>");
document.writeln("        <p class=\'card-text\'>509 UNDER CONSTRUCTION <br/> 田麻小溪正在重写网页架构……</p>");
document.writeln("    </div>");
document.writeln("	");
document.writeln("</article>");