document.writeln("<footer class=\'bg-dark mt-5\'>");
document.writeln("  <div class=\'container section\'>");
document.writeln("    <div class=\'row\'>");
document.writeln("      <div class=\'col-lg-10 mx-auto text-center\'>");
document.writeln("        <a class=\'d-inline-block mb-4 pb-2\' href=\'index.html\'>");
document.writeln("          <img loading=\'prelaod\' decoding=\'async\' class=\'img-fluid\' src=\'images/logo-white.png\' alt=\'Reporter Hugo\'>");
document.writeln("        </a>");
document.writeln("        <ul class=\'p-0 d-flex navbar-footer mb-0 list-unstyled\'>");
document.writeln("          <li class=\'nav-item my-0\'> <a class=\'nav-link\' href=\'about.html\'>关于我</a></li>");
document.writeln("          <li class=\'nav-item my-0\'> <a class=\'nav-link\' href=\'privacy-policy.html\'>隐私政策</a></li>");
document.writeln("          <li class=\'nav-item my-0\'> <a class=\'nav-link\' href=\'https://slay.one\'>小黑屋</a></li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("  <div class=\'copyright bg-dark content\'>Copyright © 2024 Makino Stream. All rights reserved.</a></div>");
document.writeln("</footer>");
document.writeln("");
document.writeln("");
document.writeln("<!-- # JS Plugins -->");
document.writeln("<script src=\'plugins/jquery/jquery.min.js\'></script>");
document.writeln("<script src=\'plugins/bootstrap/bootstrap.min.js\'></script>");
document.writeln("");
document.writeln("<!-- Main Script -->");
document.writeln("<script src=\'js/script.js\'></script>");
document.writeln("");
document.writeln("</body>");