document.writeln("<div class=\"col-12\">");
document.writeln("              <div class=\"row\">");
document.writeln("                <div class=\"col-12\">");
document.writeln("                  <nav class=\"mt-4\">");
document.writeln("                    <nav class=\"mb-md-50\">");
document.writeln("                      <ul class=\"pagination justify-content-center\">");
document.writeln("                        <li class=\"page-item\">");
document.writeln("                          <a class=\"page-link\" href=\"#!\" aria-label=\"Pagination Arrow\">");
document.writeln("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"26\" height=\"26\" fill=\"currentColor\" viewBox=\"0 0 16 16\">");
document.writeln("                              <path fill-rule=\"evenodd\" d=\"M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z\"/>");
document.writeln("                            </svg>");
document.writeln("                          </a>");
document.writeln("                        </li>");
document.writeln("                        <li class=\"page-item active \"> <a href=\"index.html\" class=\"page-link\">");
document.writeln("                            1");
document.writeln("                          </a>");
document.writeln("                        </li>");
document.writeln("                        <li class=\"page-item\"> <a href=\"#!\" class=\"page-link\">");
document.writeln("                            2");
document.writeln("                          </a>");
document.writeln("                        </li>");
document.writeln("                        <li class=\"page-item\">");
document.writeln("                          <a class=\"page-link\" href=\"#!\" aria-label=\"Pagination Arrow\">");
document.writeln("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"26\" height=\"26\" fill=\"currentColor\" viewBox=\"0 0 16 16\">");
document.writeln("                              <path fill-rule=\"evenodd\" d=\"M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z\" />");
document.writeln("                            </svg>");
document.writeln("                          </a>");
document.writeln("                        </li>");
document.writeln("                      </ul>");
document.writeln("                    </nav>");
document.writeln("                  </nav>");
document.writeln("                </div>");
document.writeln("              </div>");
document.writeln("            </div>");