document.write("  <div class=\"col-lg-4\">");
document.write("  <div class=\"widget-blocks\">");
document.write("    <div class=\"row\">");
document.write("      <div class=\"col-lg-12 col-md-6\">");
document.write("        <div class=\"widget\">");
document.write("          <h2 class=\"section-title mb-3\">推荐阅读<\/h2>");
document.write("          <div class=\"widget-body\">");
document.write("            <div class=\"widget-list\">");
document.write("			");
document.write("			");
document.write("			");
document.write("              <article class=\"card mb-4\">");
document.write("                <div class=\"card-image\">");
document.write("                  <div class=\"post-info\"> <span class=\"text-uppercase\">MAKINO STREAM<\/span>");
document.write("                  <\/div>");
document.write("                  <img loading=\"lazy\" decoding=\"async\" src=\"https:\/\/gh-proxy.org\/https:\/\/raw.githubusercontent.com\/Tenma-Saki\/sakisblog.github.io\/refs\/heads\/main\/images\/author.png\" alt=\"Post Thumbnail\" class=\"w-100\">");
document.write("                <\/div>");
document.write("                <div class=\"card-body px-0 pb-1\">");
document.write("                  <h3><a class=\"post-title post-title-sm\"");
document.write("                      href=\"article.html\"><\/a>关于我<\/h3>");
document.write("                  <p class=\"card-text\">田麻小溪是谁？是那个天天摸鱼的键盘手吗？<\/p>");
document.write("                  <div class=\"content\"> <a class=\"read-more-btn\" href=\"about.html\">阅读全文<\/a>");
document.write("                  <\/div>");
document.write("                <\/div>");
document.write("              <\/article>");
document.write("			  ");
document.write("			  ");
document.write("              <a class=\"media align-items-center\" href=\"airirobo.html\">");
document.write("                <img loading=\"lazy\" decoding=\"async\" src=\"https:\/\/gh-proxy.org\/https:\/\/raw.githubusercontent.com\/Tenma-Saki\/sakisblog.github.io\/refs\/heads\/main\/images\/post\/airirobo\/airirobo.png\" alt=\"Post Thumbnail\" class=\"w-100\">");
document.write("                <div class=\"media-body ml-3\">");
document.write("                  <h3 style=\"margin-top:-5px\">如何搭建多功能QQ群机器人 - Momoi Airi<\/h3>");
document.write("                  <p class=\"mb-0 small\">包含签到收藏、漂流瓶、海龟汤、表情包制作等超多功能！……<\/p>");
document.write("                <\/div>");
document.write("              <\/a>");
document.write("			  ");
document.write("            <\/div>");
document.write("          <\/div>");
document.write("        <\/div>");
document.write("      <\/div>");
